# Generated by Django 4.1.5 on 2023-01-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Celebrity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_no", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("yearly_earn", models.FloatField()),
                ("address", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Celebrity",
                "verbose_name_plural": "Celebrities",
            },
        ),
    ]
